modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
issueTrackerURL="https://github.com/eatAWESOME/PixelmonPokedexRewards/issues"
[[mods]]
modId="pixelmonpokedexrewards"
version="1.0.0"
displayName="PixelmonPokedexRewards"
logoFile="logo.png"
# credits=""
authors="Alden Tilley"
description='''
Rewards for progressing to completing the Pokedex in Pixelmon
'''
[[dependencies.pixelmonpokedexrewards]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.pixelmonpokedexrewards]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.pixelmonpokedexrewards]]
    modId="pixelmon"
    mandatory=true
    versionRange="[9.1,)"
    ordering="NONE"
    side="BOTH"